---
ami: "{{ redhat_ami }}"
instance_type: "t2.micro"
tag_name: "ska_ads"
tag_expireon: "2017-06-30"
data_vol_size: 30

instance_names: "{{ tag_name }}_s11"
remote_user: "ec2-user"
tag_owner: "shyam.arjarapu"
security_key: "ska-play"
security_group: "ska-sg-aws"
region: "us-west-2"
availability_zone: "{{ aws_region }}c"



# ami instances 
redhat_ami: "ami-6f68cf0f"