---
ami: "{{ redhat_ami }}"
instance_type: "t2.micro"
tag_expireon: "2017-06-30"
data_vol_size: 30
tag_name: "ska_adt"
group_name: "s1"
server_number: 1
instance_name: "{{ tag_name }}_{{ group_name }}{{ server_number }}"
server_group_name: "{{ tag_name }}_{{ group_name}}"
ssh_user: "ec2-user"
tag_owner: "shyam.arjarapu"
security_key: "ska-play"
security_group: "ska-sg-aws"
region: "us-west-2"
availability_zone: "{{ region }}c"
create_data_folder: True
data_folder: "/data"


# ami instances 
redhat_ami: "ami-6f68cf0f"