---
- name: create aws instance for replicaset 
  hosts: "ska_ssl_rs1"
  tasks:
    - include_role:
        name: "mms-automation-agent"
      vars:
        mmsGroupId: "<your group id>"
        mmsApiKey: "<your api key>"
        data_folder: "/app/data"
