---
- name: create aws instance for replicaset 
  hosts: local
  tasks:
    - include_role:
        name: aws
      vars:
        server_number: "{{ role_item }}"
        instance_type: "m4.large"
        tag_name: "ska_ads"
        group_name: "s1"
        data_vol_size: 200
      with_items: 
        - 1
        - 2
        - 3
      loop_control:
        loop_var: "role_item"

# Wait for the server disks to be ready then execute it again
- name: install and configure mongodb in replicaset instances
  hosts: "ska_ads_s1"
  roles:
    - role: mongo
      mongo_version: "2.4.14"
      tag_name: "ska_ads"
      group_name: "s1"
      replset_name: "shard1"