---
- name: create aws instance
  hosts: local
  roles:
    - role: aws
      server_number: 1
      instance_type: "t2.large"
      tag_name: "ska_ads"
      group_name: "s2"

- name: install and configure mongodb in group
  hosts: ska_ads_s2
  roles:
    - role: mongo
      mongo_version: "2.4.14"
      server_number: 1
      instance_type: "t2.large"
      tag_name: "ska_ads"
      group_name: "s2"

