---
# handlers file for mongo

- name: start mongod
  service:
    name: mongod
    state: started
  become: true

- name: stop mongod
  service:
    name: mongod
    state: stopped
  become: true

- name: restart mongod
  service:
    name: mongod
    state: restarted
  become: true

- name: reboot
  shell: (sleep 1 && /usr/sbin/reboot &)
  ignore_errors: true
  async: 1
  poll: 0
  become: true

- name: wait for ssh
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    delay: 10
    timeout: 300
    state: started
  connection: local
