- name: print the primary hostname, ip address and members
  debug: msg="private_dns [{{private_dns}}] private_ip [{{private_ip}}] member_ip [{{members}}]"

- name: initiate replica set and wait 30 sec
  shell: "mongo admin --port {{mongo_port}} --eval 'rs.initiate({ _id: \"{{replset_name}}\", members: [{ _id:0, host: \"{{private_dns}}:{{mongo_port}}\" }] }); sleep(30000);'"

# When you have security turned on, you must create user before doing anything major
- name: create root user using localhost
  shell: "mongo admin --port {{mongo_port}} --eval 'db.createUser({user: \"{{root_username}}\", pwd: \"{{root_password}}\", roles: [ \"root\" ] })'"

- name: add other members to replica set using authentication
  shell: "mongo admin -u {{root_username}} -p {{root_password}} --host {{private_dns}} --port {{mongo_port}} --eval 'rs.add(\"{{item}}:{{mongo_port}}\");'"
  with_items: "{{members}}"
