---
- name: add mongodb-{{ mongo_version[:-3] }} to yum repo 
  yum_repository: 
    name: "mongodb-{{ mongo_version[:-3] }}"
    file: "mongodb-{{ mongo_version[:-3] }}"
    description: MongoDB Repository
    baseurl: http://downloads-distro.mongodb.org/repo/redhat/os/x86_64/
    gpgcheck: no
    enabled: yes
  become: true
  when: mongo_version | version_compare('2.4.14', operator='le', strict=True)

- name: install mongodb ce {{ mongo_version }}
  yum: 
    name: "{{item}}-{{ mongo_version }}"
    state: present
    exclude: "mongodb-org,mongodb-org-server"
  become: true
  with_items: 
    - "mongo-10gen"
    - "mongo-10gen-server"
  when: mongo_version | version_compare('2.4.14', operator='le', strict=True)

- name: check for existence of {{ data_folder }}/db folder
  stat: 
    path: "{{ data_folder }}/db"
  register: data_folder_check

- name: create the data folder and start mongod
  file: 
    path: "{{ item }}"
    owner: mongod
    group: mongod
    state: directory
    recurse: yes
  become: true
  with_items:
    - "{{ data_folder }}"
    - "{{ data_folder }}/db"
  when: data_folder_check.stat.exists == False

- name: copy the mongod.conf 
  template:
    src: "mongod_v{{ mongo_version[:-3] }}.conf"
    dest: /etc/mongod.conf
  become: true

- name: disable the selinux
  selinux:
    state: disabled
    policy: targeted
  become: true
  notify: 
    - reboot
    - wait for ssh