---
- name: install xfsprogs and xfsdump
  yum: 
    name: {{item}}
    state: present
  with_items:
    - xfsprogs
    - xfsdump
  become: true
  
- name: check if {{ data_folder }} folder already exists
  stat: 
    path: {{ data_folder }}
  register: check_folder

- name: format /dev/xvdb volume as XFS
  filesystem:
    fstype: xfs
    dev: /dev/xvdb
    # force: True
  become: true
  when: check_folder.stat.exists == False

- name: create {{ data_folder }} folder at root
  file:
    path: {{ data_folder }}
    state: directory
  become: true
  when: check_folder.stat.exists == False

- name: mount the device /dev/xvdb on /data
  mount:
    path: /data
    src: /dev/xvdb
    fstype: xfs
    opts: noatime
    state: mounted
  become: true
  when: check_folder.stat.exists == False