---
# defaults file for ssl-create-self-signed-rootca

ssl_folder: "/etc/ssl"
ssl_filename: "mongodb"
ssl_private_key: "{{ssl_folder}}/private/{{ssl_filename}}.key"
ssl_public_crt: "{{ssl_folder}}/public/{{ssl_filename}}.crt"
ssl_csr_file: "{{ssl_folder}}/sign_requests/{{ssl_filename}}.csr"
cn_prefix: "/C=US/ST=Texas/L=Austin/O=MongoDB/OU=Operations"