---
- name: check if AWS EC2 instance already exists
  ec2_remote_facts:
    region: "{{ region }}"
    filters:
      instance-state-name: running
      "tag:Name": "{{ instance_name }}"
  register: instance_check

- include: create.instance.yml
  when: instance_check.instances.0 is undefined

- include: mount.data.device.yml
  when: instance_check.instances.0 is undefined