---
- name: check if AWS EC2 instance already exists
  ec2_remote_facts:
    region: "{{ region }}"
    filters:
      instance-state-name: running
      "tag:Name": "{{ instance_name }}"
  register: instance_check

- name: if not exists already, create an AWS EC2 instance
  ec2:
     key_name: "{{ security_key }}"
     region: "{{ region }}"
     zone: "{{ availability_zone }}"
     group: "{{ security_group }}"
     instance_type: "{{ instance_type }}"
     image: "{{ ami }}"
     wait: yes
     instance_tags:
       "Name": "{{ instance_name }}"
       "owner": "{{ tag_owner }}"
       "expire-on": "{{ tag_expireon }}"
     count: 1
     volumes:
       - device_name: /dev/sda1
         volume_type: gp2
         volume_size: 10
         delete_on_termination: true
       - device_name: /dev/xvdb
         volume_type: gp2
         volume_size: "{{ data_vol_size }}"
         delete_on_termination: true
  register: instance_output
  when: instance_check.instances.0 is undefined