---

- name: find the sign requests and create the certificates using the rootCA
  find:
    paths: "{{ssl_folder}}/sign_requests"
    patterns: '*.csr'
  register: requests

- name: for each file create the 
  become: true
  shell: "openssl x509 -req -in {{item.path}} -CA {{ssl_public_crt}} -CAkey {{ssl_private_key}}  -CAcreateserial -out {{ssl_sign_cert}} -days 365"
  vars:
    ssl_sign_cert: "{{item.path | regex_replace('sign_requests', 'public') | regex_replace('csr$', 'crt')}}"
  with_items: "{{requests.files}}"

- name: copy all the crt files from signing server to local machine
  become: true
  synchronize: 
    mode: pull
    src: "{{ssl_folder}}/public/*.crt"
    dest: "{{local_crt_folder}}"
