---
# defaults file for opsmanager
opsmgr_version: "3.4.7.479-1"
replicaset_appdb: "appdb"
replicaset_oplogdb: "oplogdb"
port_appdb: "27000"
port_oplogdb: "27001"
data_folder: "/data"
root_username: "superuser"
root_password: "password"
opsmanager_uri: "http://ec2-54-214-214-22.us-west-2.compute.amazonaws.com:8080"
automation_agent_version: "3.2.14.2187-1.x86_64.rhel7"