---
proxy_http: ""
proxy_https: ""
use_proxy: false
target_version: "4.0.0"
service_name: "mongod"
binary_filename: "mongodb-linux-x86_64-rhel70-{{target_version}}"
tgz_filename: "{{binary_filename}}.tgz"
download_uri: "https://fastdl.mongodb.org/linux/{{tgz_filename}}"
releases_dir: "/opt/mongodb"
runas_service_user: "mongod" #servicepmongo
runas_service_group: "mongod" #