---

- name: cleanup - remove temporary ssl files & directories on local machine
  hosts:  "local"
  tasks:
    - name: delete the temporary directories
      file: 
        path: "/tmp/openssl"
        state: absent
    - name: create temporary ssl files & directories on local machine
      file:
        state: directory
        path: "/tmp/openssl/{{ item }}"
        mode: 0755
      with_items:
        - crt
        - csr
    
- name: create self signed root certificate authority
  hosts: "ska_ssl_rs1[0]"
  roles:
    - role: "ssl-create-rootca"

- name: create cerficiate signing request for all servers
  hosts: "ska_ssl_rs1"
  roles:
    - role: "ssl-create-csr"

- name: upload all the csr files from local machine to signing servers 
  hosts:  "ska_ssl_rs1[0]"
  roles:
    - role: "ssl-upload-csr"

- name: create certs for the csr requests
  hosts:  "ska_ssl_rs1[0]"
  roles:
    - role: "ssl-create-cert"

- name: copy all the crt file back onto the servers 
  hosts: "ska_ssl_rs1"
  roles:
    - role: "ssl-upload-crt"

- name: cleanup - remove temporary ssl files & directories on local machine
  hosts:  "local"
  tasks:
    - name: delete the temporary directories
      file: 
        path: "/tmp/openssl"
        state: absent

# - name: cleanup - remove all ssl files directories
#   hosts:  "ska_ssl_rs1"
#   tasks:
#     - name: create directories for holding the certificates
#       become: true
#       file: 
#         path: "/etc/ssl/{{item}}"
#         state: absent
#       with_items:
#         - csr
#         - sign_requests
#         - public
#         - private
