---

- name: provision aws instance for ops manager
  hosts: local
  tasks:
    - include_role:
        name: aws
      vars:
        group_name: "opsmgr"
        instance_type: "t2.large"
        data_vol_size: 60
      with_items:
        - "1"
        - "2"
        - "3"
      loop_control:
        loop_var: server_number  
