---
- name: create aws instance for replicaset 
  hosts: local
  tasks:
    - include_role:
        name: aws
      vars:
        ami: "ami-223f945a"
        instance_type: "t2.micro"
        data_vol_size: 100
        tag_name: "ska_ssl"
        group_name: "rs1"
        server_number: "{{ role_item }}"
        tag_expireon: "2019-12-30"
      with_items: 
        - '01'
        - '02'
        - '03'
      loop_control:
        loop_var: "role_item"