---

- name: copy all the csr requests 
  hosts:  "local"
  tasks:
    - name: create directories for holding the certificates
      file: 
        path: "/tmp/openssl/{{item}}"
        state: directory
        mode: 0755
      with_items:
        - csr
        - crt
        - pem



- name: copy all the csr requests 
  hosts:  "ska_ssl_rs1[0]"
  roles:
    - role: "ssl-sign-csr"


# - name: create cerficiate signing request file
#   hosts: "ska_ssl_rs1[0]"
#   roles:
#     - role: "ssl-sign-csr"
