---

- name: upgrade the secondaries
  hosts: mongo_replicaset
  tasks:
    - set_fact:
        current_version: "4.0.0"
        target_version: "4.0.2"
        primary_turn: False
    - include_role:
        name: "upgrade-mongo"
        tasks_from: "download.binaries"
    - include_role:
        name: "upgrade-mongo"
        tasks_from: "load.status"

- name: upgrade the secondaries
  hosts: mongo_replicaset
  serial: 1
  roles:
    - role: "upgrade-mongo"

- name: upgrade the primary
  hosts: mongo_replicaset
  tasks:
    - set_fact:
        primary_turn: True
    - include_role: 
        name: "upgrade-mongo"

# - name: download and extract the mongodb version binaries
#   hosts: mongo_replicaset
#   serial: 1
#   vars:
#     current_version: "4.0.0"
#     target_version: "4.0.1"
#     primary_turn: True
#   tasks:
#     - include_role: 
#         name: "upgrade-mongo"

# - name: download and extract the mongodb version binaries
#   hosts: mongo_replicaset
#   tasks:
#     - include_role:
#         name: "upgrade-mongo"
#         tasks_from: "download.binaries"
#       vars:
#         target_version: "4.0.0"

# - name: connect each host and set is_primary flag
#   hosts: "mongo_replicaset"
#   serial: 1
#   vars:
#     current_version: "4.0.0"
#     target_version: "4.0.1"
#   tasks:
#     - name: "upgrade each secondary"
#       include_role:
#         name: "upgrade-mongo"
#         tasks_from: "upgrade.secondary"

# - name: connect each host and set is_primary flag
#   hosts: "mongo_replicaset"
#   serial: 1
#   vars:
#     current_version: "4.0.0"
#     target_version: "4.0.1"
#   tasks:
#     - name: "step down the current primary"
#       include_role:
#         name: "upgrade-mongo"
#         tasks_from: "stepdown.primary"

# - name: connect each host and set is_primary flag
#   hosts: "mongo_replicaset"
#   serial: 1
#   vars:
#     current_version: "4.0.0"
#     target_version: "4.0.1"
#   tasks:
#     - name: "upgrade the previous primary"
#       include_role:
#         name: "upgrade-mongo"
#         tasks_from: "upgrade.secondary"
        