---

- name: copy all the crt certificates 
  hosts: "ska_ssl_rs1[0]"
  roles:
    - role: "ssl-upload-crt"

# - name: cleanup - remove all ssl files directories
#   hosts:  "ska_ssl_rs1"
#   tasks:
#     - name: create directories for holding the certificates
#       become: true
#       file: 
#         path: "/etc/ssl/{{item}}"
#         state: absent
#       with_items:
#         - csr
#         - sign_requests
#         - public
#         - private


# - name: cleanup - remove temporary ssl files & directories on local machine
#   hosts:  "local"
#   tasks:
#     - name: delete the temporary directories
#       file: 
#         path: "/tmp/openssl"
#         state: absent
