---
- name: check if the [{{releases_dir}}/{{binary_filename}}] folder already exists
  stat: 
    path: "{{releases_dir}}/{{binary_filename}}"
  register: check_folder

- block:

  - name: download the binaries from [{{download_uri}}]
    become: true
    get_url:
      url: "{{download_uri}}"
      dest: "{{releases_dir}}/{{tgz_filename}}"
      mode: 0600
      owner: "{{runas_service_user}}"
      group: "{{runas_service_group}}"
      force: yes 

  - name: untar the binaries as [{{runas_service_user}}] user
    become: yes
    become_user: "{{runas_service_user}}"
    unarchive:
      src: "{{releases_dir}}/{{tgz_filename}}"
      dest: "{{releases_dir}}"
      remote_src: yes

  - name: delete the tar file [{{releases_dir}}/{{tgz_filename}}]
    become: yes
    file:
      path: "{{releases_dir}}/{{tgz_filename}}"
      state: absent

  when: check_folder.stat.exists == False
