---
- name: upgrade only if secondary server and it's secondarys turn - {{primary_turn == False}}
  import_tasks: upgrade.secondary.yml
  when: (primary_turn == False) and (mongod_version != target_version) and (is_primary == False)

- block:
  - name: stepdown only if primary server and it's primaries turn - {{primary_turn}}
    import_tasks: stepdown.primary.yml
  - name: upgrade only if primary server and it's primaries turn - {{primary_turn}}
    import_tasks: upgrade.secondary.yml
  when: (primary_turn == True) and (mongod_version != target_version) and (is_primary == True)
